#!/usr/bin/env python3

# Copyright 2014 Michael Cuffaro
# 
# This file is part of mccal.
# 
# mccal is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# mccal is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with mccal.  If not, see <http://www.gnu.org/licenses/>.

import time
import os

HOME = os.environ['HOME']
CAL_FILENAME = f'{HOME}/.mycalendar.txt'
PROCESSED_EVENTS_FILENAME = f'{HOME}/.mycalendar_processed.txt'
PAUSE_FILENAME = f'{HOME}/.pause_mccal'
SLEEP_VAL = 300
with open('/etc/timezone') as tz_file:
  TIME_ZONE = tz_file.readline().rstrip()


def main():
  while True:
    if os.path.exists(PAUSE_FILENAME):
      time.sleep(SLEEP_VAL)
      continue

    break


if __name__ == "__main__":
  main()
