#!/usr/bin/env python3

# Copyright 2014-2024 Michael Cuffaro
# 
# This file is part of mccal.
# 
# mccal is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# mccal is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with mccal.  If not, see <http://www.gnu.org/licenses/>.

import argparse
import re


def get_events(calendar_file, year, month, day):
  with open(calendar_file) as f:
    lines = []
    for line in f:
      line = line.rstrip('\n')
      grep_string = f"{year}"
      if month:
        grep_string += f"-0*{month}"
      if day:
        grep_string += f"-0*{day}"
      if re.search(grep_string, line):
        lines.append(line)
    return lines


def sort_events(events):
  pruned_events = []
  for event in events:
    # remove the initial id portion of the line:
    event = re.sub("^(SNOOZE )?ID:\S+ ", "", event)
    # remove date and time separators ("/" and ":")
    event = re.sub(
      r"([0-9]{1,4})-([0-9]{1,2})-([0-9]{1,2})\s+([0-9]{1,2}):([0-9]{1,2})\s+(.*)",
      "\g<1> \g<2> \g<3> \g<4> \g<5> \g<6>",
      event
    );
    event = event.split(' ', maxsplit=5)
    for i in range(0,5):
      event[i] = int(event[i])
    pruned_events.append(event)

  # Sort the entries:
  sorted_events = sorted(pruned_events, key=lambda x: (x[0], x[1], x[2], x[3], x[4]))
  # Add back the separators:
  sorted_events = [
    re.sub(
      r"([0-9]{1,4})\s([0-9]{1,2})\s([0-9]{1,2})\s([0-9]{1,2})\s([0-9]{1,2})\s(.*)",
      "\g<1>-\g<2>-\g<3> \g<4>:\g<5> \g<6>",
      f"{x[0]} {x[1]} {x[2]} {x[3]} {x[4]} {x[5]}"
    )
    for x in sorted_events
  ]
  return sorted_events


def main(calendar_file, modifier, time_period):
  if m := re.fullmatch(r'(\d{1,4})(-(\d{1,2}))?(-(\d{1,2}))?', time_period):
    year = int(m.groups()[0])
    month = int(m.groups()[2])
    day = int(m.groups()[4])
    events = get_events(calendar_file, year, month, day)
    sorted_events = sort_events(events)
    print('\n'.join(sorted_events))
  elif re.fullmatch(r'today', time_period):
    print("today")
  elif re.fullmatch(r'month', time_period):
    print("month")
  elif re.fullmatch(r'year', time_period):
    print("year")
  else:
    print("Miscellaneous")


if __name__ == "__main__":
  parser = argparse.ArgumentParser(description="TODO: Add description")
  parser.add_argument('-f', '--calendar_file')
  parser.add_argument('MODIFIER', choices=['next', 'last'], nargs='?')
  parser.add_argument('TIME_PERIOD', help="Can be one of: year, month, week, monday, \
  tuesday, wednesday, thursday, friday, saturday, sunday, today, tomorrow, yesterday \
  yyyy-mm-dd, yyyy-mm, yyyy")
  args = parser.parse_args()
  main(args.calendar_file, args.MODIFIER, args.TIME_PERIOD)
